language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  matrix:
    - UPGRADE=7.x-1.x-dev
  global:
    secure: Jc9tSi/yf5qy1Bz0NipXxixXFYMgksorzHReDLGoeSRGG/5aCO2Py1/SQko6Y6YzR0fvuByWXFM8T8Ob0+soeC26CnLygARm50h4Px5vv9iW0RUd0jkmMqMz67fIrAOptfp1lbHe2m9Xe91XhBDTcF6HhdXXKc71y5WsRAawoPA=

matrix:
  fast_finish: true

install:
  # Make some variables available to the travis-ci.sh script.
  - export UPDATE TRAVIS_BUILD_DIR
  # Copy the script into a stable location.
  - cp scripts/travis-ci.sh $HOME/
  # Allow script to be exectuted
  - chmod +x $HOME/travis-ci.sh
  # Move to the directory above, where we should remain.
  - cd ..
  # Start by doing system installation.
  - $HOME/travis-ci.sh system-install

before_script:
  - $HOME/travis-ci.sh before-tests

script:
  - $HOME/travis-ci.sh run-tests

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID

after_success:
  - $HOME/travis-ci.sh after-tests

notifications:
  email:
    recipients:
      - hotsauce-ci@googlegroups.com
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#hotsauce"
    on_success: always
    on_failure: always
